"use strict";

export default {
    STORE_CHANGED: "STORE_CHANGED",

    PUSH_RANDOM_VIEW: "PUSH_RANDOM_VIEW",
    POP_RANDOM_VIEW: "POP_RANDOM_VIEW",
    RANDOMIZE_ALL_VIEWS: "RANDOMIZE_ALL_VIEWS",

    POP_HISTORY: "POP_HISTORY"
}